#define SCOREP_USER_ENABLE

#include <roco2/scorep.hpp>

SCOREP_USER_METRIC_GLOBAL(experiment_metric)
SCOREP_USER_METRIC_GLOBAL(thread_metric)
SCOREP_USER_METRIC_GLOBAL(frequency_metric)
SCOREP_USER_METRIC_GLOBAL(ddcm_metric)
SCOREP_USER_METRIC_GLOBAL(c_state_limit_metric)
SCOREP_USER_METRIC_GLOBAL(utility_metric)
