# Find X86_adapt library/headers
if (X86ADAPT_LIBRARIES AND X86ADAPT_INCLUDE_DIRS)
  set (X86Adapt_FIND_QUIETLY TRUE)
endif (X86ADAPT_LIBRARIES AND X86ADAPT_INCLUDE_DIRS)

find_path(X86ADAPT_INCLUDE_DIRS NAMES x86_adapt.h)
find_library(X86ADAPT_LIBRARIES NAMES x86_adapt)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(X86Adapt DEFAULT_MSG
  X86ADAPT_LIBRARIES
  X86ADAPT_INCLUDE_DIRS)

mark_as_advanced(X86ADAPT_INCLUDE_DIRS X86ADAPT_LIBRARIES)