# Find NUMA
if (NUMA_LIBRARIES AND NUMA_INCLUDE_DIRS)
  set (NUMA_FIND_QUIETLY TRUE)
endif (NUMA_LIBRARIES AND NUMA_INCLUDE_DIRS)

find_path(NUMA_INCLUDE_DIRS NAMES numa.h HINTS ${NUMA_INCLUDE_DIRS} ${NUMA_ROOT_DIR}/include ENV CPATH C_INCLUDE_PATH)
find_library(NUMA_LIBRARIES NAMES numa HINTS ${NUMA_LIBRARIES} ${NUMA_ROOT_DIR}/lib ENV LIBRARY_PATH LD_LIBRARY_PATH)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NUMA DEFAULT_MSG
  NUMA_LIBRARIES
  NUMA_INCLUDE_DIRS)

if(NUMA_FOUND)
    add_library(NUMA::NUMA UNKNOWN IMPORTED GLOBAL)
    set_target_properties(NUMA::NUMA PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES "C"
        IMPORTED_LOCATION "${NUMA_LIBRARIES}"
        INTERFACE_INCLUDE_DIRECTORIES "${NUMA_INCLUDE_DIRS}"
    )
endif()

mark_as_advanced(NUMA_INCLUDE_DIRS NUMA_LIBRARIES)
