# find CpuFreq
if(CPUFREQ_LIBRARIES AND CPUFREQ_INCLUDE_DIRS)
  set (Cpufreq_FIND_QUIETLY TRUE)
endif (CPUFREQ_LIBRARIES AND CPUFREQ_INCLUDE_DIRS)

find_path(CPUFREQ_INCLUDE_DIRS NAMES cpufreq.h HINTS ENV C_INCLUDE_PATH)
find_library(CPUFREQ_LIBRARIES NAMES libcpufreq.a cpufreq HINTS ENV LIBRARY_PATH LD_LIBRARY_PATH)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Cpufreq DEFAULT_MSG
  CPUFREQ_LIBRARIES
  CPUFREQ_INCLUDE_DIRS)

mark_as_advanced(CPUFREQ_INCLUDE_DIRS CPUFREQ_LIBRARIES)
