# find CpuFreq
if(CPUFREQ_LIBRARIES AND CPUFREQ_INCLUDE_DIRS)
  set (Cpufreq_FIND_QUIETLY TRUE)
endif (CPUFREQ_LIBRARIES AND CPUFREQ_INCLUDE_DIRS)

find_path(CPUFREQ_INCLUDE_DIRS NAMES cpufreq.h HINTS ${CPUFREQ_INCLUDE_DIRS} ${CPUFREQ_ROOT_DIR}/include ENV CPATH C_INCLUDE_PATH)
find_library(CPUFREQ_LIBRARIES NAMES libcpufreq.a cpufreq HINTS ${CPUFREQ_LIBRARIES} ${CPUFREQ_ROOT_DIR}/lib ENV LIBRARY_PATH LD_LIBRARY_PATH)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CpuFreq DEFAULT_MSG CPUFREQ_LIBRARIES CPUFREQ_INCLUDE_DIRS)

if(CpuFreq_FOUND)
    add_library(Cpufreq::Cpufreq UNKNOWN IMPORTED GLOBAL)
    set_target_properties(Cpufreq::Cpufreq PROPERTIES
        IMPORTED_LINK_INTERFACE_LANGUAGES "C"
        IMPORTED_LOCATION "${CPUFREQ_LIBRARIES}"
        INTERFACE_INCLUDE_DIRECTORIES "${CPUFREQ_INCLUDE_DIRS}"
    )
endif()

mark_as_advanced(CPUFREQ_INCLUDE_DIRS CPUFREQ_LIBRARIES)
